/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alta`; params?: Router.UnknownInputParams; } | { pathname: `/Detalles`; params?: Router.UnknownInputParams; } | { pathname: `/Error`; params?: Router.UnknownInputParams; } | { pathname: `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `/pago`; params?: Router.UnknownInputParams; } | { pathname: `/Qr`; params?: Router.UnknownInputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/cobro`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alta`; params?: Router.UnknownOutputParams; } | { pathname: `/Detalles`; params?: Router.UnknownOutputParams; } | { pathname: `/Error`; params?: Router.UnknownOutputParams; } | { pathname: `/movimientos`; params?: Router.UnknownOutputParams; } | { pathname: `/pago`; params?: Router.UnknownOutputParams; } | { pathname: `/Qr`; params?: Router.UnknownOutputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/cobro`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/alta${`?${string}` | `#${string}` | ''}` | `/Detalles${`?${string}` | `#${string}` | ''}` | `/Error${`?${string}` | `#${string}` | ''}` | `/movimientos${`?${string}` | `#${string}` | ''}` | `/pago${`?${string}` | `#${string}` | ''}` | `/Qr${`?${string}` | `#${string}` | ''}` | `/tranferencia${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/cobro${`?${string}` | `#${string}` | ''}` | `/scanner${`?${string}` | `#${string}` | ''}` | `/scanner/Overlay${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alta`; params?: Router.UnknownInputParams; } | { pathname: `/Detalles`; params?: Router.UnknownInputParams; } | { pathname: `/Error`; params?: Router.UnknownInputParams; } | { pathname: `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `/pago`; params?: Router.UnknownInputParams; } | { pathname: `/Qr`; params?: Router.UnknownInputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/cobro`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownInputParams; };
    }
  }
}
